### ISSUE TITLE
Add a config file

### ISSUE THREAD

**Issue by hvaldecantos** [hvaldecantos/pcer#1]
For now, the config file will keep the dimension and position of the windows.

**Comment by harry-swan** [comment]
I made a change that saves the dimension and position of the code_viewer to a text file. I can easily do the same things to the other windows but since we don't track eyes for those, I don't think that is necessary.

**Comment by hvaldecantos** [comment]
Take a look at the PcerWindow class, a super class of all windows in the project. For now, I think we need only one size for all the windows. We can use a yaml (or similar) format, and the file should be in the root directory of the project.

**Comment by harry-swan** [comment]
I've been trying to load a YAML file like this:
`with open(os.getcwd()[:-4] + "config.yml", 'r') as stream:`
`    try:`
`        self.config = yaml.safe_load(stream)`
`    except yaml.YAMLError as exc:`
`        print(exc)`
I can't get it to run correctly and not run the exception, so it just prints "864" and so I can't use the file to set a height or width.

This is the content in the YAML file:
window_size:
	width: 800
	height: 300

Do you have any suggestions for ways to fix this issue?

**Comment by harry-swan** [comment]
A yaml file now contains dimensions for the CodeViewer class, it also sets them in the PcerWindow class even though none of the windows use the information from that class yet.

**Comment by hvaldecantos** [comment]
We need to add a section in the README file that explains the need of the `config.yml` file and the configuration parameters that it should contain.
