### ISSUE TITLE
Add a pop-up warning in the participant form

### ISSUE THREAD

**Issue by hvaldecantos** [hvaldecantos/pcer#12]
When clicking the 'continue' button in the participant form, the system should warn in the following cases:

- With no active participant (participant_id=None, participant_group=None)

  - If ID exist, the system suggests the user to use the open function. The window stays in the participant form and loads the current participant status (empty).

- With a current active participant (ID=xxx, Group={DCI/OO})

  - If ID is different from the current `participant_id`, the system suggests the user to use the open function. The window stays in the participant form and loads the current participant status.

**Comment by KaleChinmay** [comment]
This issue requires correcting the code status text and some extra modifications in load button as well apart from "continue" button. @hvaldecantos

**Comment by KaleChinmay** [comment]
I have added the popup message to continue button but if load button is not modified, it never advances to Task window
