### ISSUE TITLE
Create a folder hierarchy for data files

### ISSUE THREAD

**Issue by KaleChinmay** [hvaldecantos/pcer#13]
We need to create a folder structure for all the data files like : 
 1. Files which we will use to populate QT Window with code and other text as required.
 2. Files which we will generate to save user data like "db" file
Suggested structure:
pcer 
-----> Resource
-----> pcer
-----> bin
-----> README

**Comment by KaleChinmay** [comment]
I will create the above structure if thats okay

**Comment by hvaldecantos** [comment]
We can leave the `db.json` and the `config.yml` in the root directory, this seems to be the standard way  to go in small systems. For the material needed for the experiment, I think a `resource/` directory is enough. Something like:

    ./resource/<paradigm>/<system name>/code
    ./resource/<paradigm>/<system name>/tasks

This resource directory should not be versioned as it would work like the configuration of the experiment to run.

**Comment by hvaldecantos** [comment]
I have already added the resource directory into the .gitignore file

**Comment by hvaldecantos** [comment]
The resource directory structure is explained in the [README.md](https://github.com/hvaldecantos/pcer/blob/master/README.md) file.
